name: Free Ubuntu SSH VM
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2

      - name: Preparing Linux Environment
        run: sudo apt-get update

      - name: Setting Up Ubuntu SSH
        run: bash linux-ssh.sh
        env:
          LINUX_USER_PASSWORD: ${{ secrets.LINUX_USER_PASSWORD }}
          LINUX_MACHINE_NAME: FreeVPS   # optional
          
      - name: Keep Runner Alive
        run: sleep infinity