name: Windows-Ngrok-RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Enable RDP
      run: |
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "UserAuthentication" -Value 1

    - name: Set runner password
      run: |
        net user runneradmin P@ssw0rd123

    - name: Download ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip
        Remove-Item ngrok.zip

    - name: Authenticate ngrok
      run: |
        .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Start ngrok RDP tunnel (TCP 3389)
      run: |
        Start-Process -NoNewWindow -FilePath .\ngrok\ngrok.exe -ArgumentList "tcp 3389"

    - name: Start ngrok HTTP tunnel (Docker / web apps)
      run: |
        Start-Process -NoNewWindow -FilePath .\ngrok\ngrok.exe -ArgumentList "http 80"

    - name: Show connection info
      run: |
        echo "====================================="
        echo "RDP USER: runneradmin"
        echo "RDP PASS: P@ssw0rd123"
        echo "Ngrok links will appear in logs above"
        echo "====================================="

    - name: Keep VM alive
      run: |
        while ($true) { Start-Sleep -Seconds 60 }